/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Curotec AsPI
 * Curotec API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePostRequest {
  /** @minLength 1 */
  title: string;
  /**
   * Content of the post
   * @minLength 1
   */
  content: string;
  published: boolean;
}
