/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Curotec AsPI
 * Curotec API Documentation
 * OpenAPI spec version: 1.0.0
 */

export * from "./createPostRequest";
export * from "./loginRequest";
export * from "./loginResponse";
export * from "./postResponse";
export * from "./registerRequest";
export * from "./updatePostRequest";
export * from "./userResponse";
