/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Curotec AsPI
 * Curotec API Documentation
 * OpenAPI spec version: 1.0.0
 */

export interface PostResponse {
  id?: number;
  title?: string;
  content?: string;
  published?: boolean;
  authorId?: number;
  createdAt?: string;
}
